server.port: 8080
eureka.client.service-url.defaultZone: http://localhost:8761/eureka
jwt:
  secretKey: dGhpcy1pcy1hLXN1cGVyLXNlY3VyZS1qd3Qtc2VjcmV0LWtleS10aGF0LWlzLTY0LWNoYXJzLWxvbmchIQ==

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**
              filters:
                - StripPrefix=2

            - id: post-service
              uri: lb://POST-SERVICE
              predicates:
                - Path=/api/v1/post/**
              filters:
                - StripPrefix=2
                - name: AuthenticationFilter

            - id: connection-service
              uri: lb://CONNECTION-SERVICE
              predicates:
                - Path=/api/v1/connection/**
              filters:
                - StripPrefix=2
                - name: AuthenticationFilter