spring.application.name=post-service


server.servlet.context-path=/api/v1/post
server.port = 9020

spring.datasource.url=jdbc:postgresql://localhost:5432/postDB
spring.datasource.username=postgres
spring.datasource.password=Root
spring.jpa.hibernate.ddl-auto=create
