spring.application.name=user-service

server.servlet.context-path=/users
server.port = 9010

spring.datasource.url=jdbc:postgresql://localhost:5432/userDB
spring.datasource.username=postgres
spring.datasource.password=Root
spring.jpa.hibernate.ddl-auto=create

jwt.secretKey = dGhpcy1pcy1hLXN1cGVyLXNlY3VyZS1qd3Qtc2VjcmV0LWtleS10aGF0LWlzLTY0LWNoYXJzLWxvbmchIQ==

eureka.client.service-url.defaultZone= http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true