spring.application.name=user-service

server.servlet.context-path=/users
server.port = 9010

spring.datasource.url=jdbc:postgresql://localhost:5432/userDB
spring.datasource.username=postgres
spring.datasource.password=Root
spring.jpa.hibernate.ddl-auto=create

jwt.secretKey = hieruqgiureoeyncuctiountiov58ctnwy498th6v4jihot2nc4ht5uthnfier76q34uihtre8ryv5rniug

eureka.client.service-url.defaultZone= http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true