spring.application.name=connection-service

server.port = 9030
server.servlet.context-path=/connection

spring.neo4j.uri=neo4j+s://195bc2d4.databases.neo4j.io
spring.neo4j.authentication.username=195bc2d4
spring.neo4j.authentication.password=J26jE_Xy174JGKDBWFL4q_WwhXBOaGFrk4nv4CPKwjY

eureka.client.service-url.defaultZone= http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

## Force schema generation on startup
#spring.data.neo4j.schema-generation.mode=create
#spring.data.neo4j.schema-generation.scripts.action=create


## Database name (creates/uses this specific database)
#spring.neo4j.database=connection-service-db

## Clear database on startup (if supported)
#spring.data.neo4j.schema-generation.drop-mode=create-drop